using CQRSMediaTr.Domain;
using CQRSMediaTr.Infrastructure.Persistance;

namespace CQRSMediaTr.Seed
{
    public class DbSeeder
    {
        public static void Seed(AppDbContext appDbContext)
        {
            if (!appDbContext.Brands.Any())
            {
                appDbContext.Brands.AddRange
                (
                     new Brand { Name = "Polar" },
                     new Brand { Name = "Mahou" },
                     new Brand { Name = "Alhambra" },
                     new Brand { Name = "Corona" },
                     new Brand { Name = "Heineken" },
                     new Brand { Name = "Budweiser" },
                     new Brand { Name = "Guinness" },
                     new Brand { Name = "Amstel" },
                     new Brand { Name = "Estrella Damm" },
                     new Brand { Name = "San Miguel" },
                     new Brand { Name = "Paulaner" },
                     new Brand { Name = "Beck’s" },
                     new Brand { Name = "Carlsberg" },
                     new Brand { Name = "Coors" },
                     new Brand { Name = "Stella Artois" },
                     new Brand { Name = "Modelo" },
                     new Brand { Name = "Quilmes" },
                     new Brand { Name = "Pilsner Urquell" },
                     new Brand { Name = "Dos Equis" },
                     new Brand { Name = "Leffe" },
                     new Brand { Name = "Tiger" },
                     new Brand { Name = "Peroni" },
                     new Brand { Name = "Kirin" },
                     new Brand { Name = "Asahi" },
                     new Brand { Name = "Tsingtao" },
                     new Brand { Name = "Sapporo" },
                     new Brand { Name = "Grolsch" },
                     new Brand { Name = "Hoegaarden" },
                     new Brand { Name = "Blue Moon" },
                     new Brand { Name = "Samuel Adams" },
                     new Brand { Name = "Brooklyn Brewery" },
                     new Brand { Name = "Sierra Nevada" },
                     new Brand { Name = "Lagunitas" },
                     new Brand { Name = "Anchor Steam" },
                     new Brand { Name = "Goose Island" },
                     new Brand { Name = "Molson" },
                     new Brand { Name = "Labatt" },
                     new Brand { Name = "Foster’s" },
                     new Brand { Name = "Victoria Bitter" },
                     new Brand { Name = "Montejo" },
                     new Brand { Name = "Cusqueña" },
                     new Brand { Name = "Brahma" },
                     new Brand { Name = "Skol" },
                     new Brand { Name = "Itaipava" },
                     new Brand { Name = "Antarctica" },
                     new Brand { Name = "Patagonia" },
                     new Brand { Name = "Andes Origen" },
                     new Brand { Name = "Schneider" },
                     new Brand { Name = "Warsteiner" },
                     new Brand { Name = "Zulia" },
                     new Brand { Name = "Tovar" },
                     new Brand { Name = "Presidente" },
                     new Brand { Name = "Erdinger" },

                     // Nuevas marcas internacionales
                     new Brand { Name = "Snow" },
                     new Brand { Name = "Harbin" },
                     new Brand { Name = "Bud Light" },
                     new Brand { Name = "Westvleteren" },
                     new Brand { Name = "Stiegl" },
                     new Brand { Name = "Menabrea" },
                     new Brand { Name = "Affligem" },
                     new Brand { Name = "Baltika" },
                     new Brand { Name = "Bitburger" },
                     new Brand { Name = "Chimay" },
                     new Brand { Name = "Delirium Tremens" },
                     new Brand { Name = "Efes" },
                     new Brand { Name = "Franziskaner" },
                     new Brand { Name = "Jupiler" },
                     new Brand { Name = "Kozel" },
                     new Brand { Name = "La Trappe" },
                     new Brand { Name = "Löwenbräu" },
                     new Brand { Name = "McEwan’s" },
                     new Brand { Name = "Mythos" },
                     new Brand { Name = "Orval" },
                     new Brand { Name = "Red Stripe" },
                     new Brand { Name = "Singha" },
                     new Brand { Name = "Sol" },
                     new Brand { Name = "Tecate" },
                     new Brand { Name = "Tuborg" },
                     new Brand { Name = "Weihenstephaner" },
                     new Brand { Name = "Westmalle" },
                     new Brand { Name = "Yanjing" },
                     new Brand { Name = "Zlatý Bažant" },
                     new Brand { Name = "Bohemia" },
                     new Brand { Name = "Indio" },
                     new Brand { Name = "Carta Blanca" },
                     new Brand { Name = "Victoria" },
                     new Brand { Name = "Sol Clamato" },
                     new Brand { Name = "Michelob Ultra" },
                     new Brand { Name = "Rolling Rock" },
                     new Brand { Name = "Yuengling" },
                     new Brand { Name = "Rainier" },
                     new Brand { Name = "Narragansett" },
                     new Brand { Name = "Genesee" },
                     new Brand { Name = "Iron City" },
                     new Brand { Name = "Red Dog" },
                     new Brand { Name = "Old Milwaukee" },
                     new Brand { Name = "Pabst Blue Ribbon" },
                     new Brand { Name = "Hamm’s" },
                     new Brand { Name = "Schlitz" },
                     new Brand { Name = "Miller High Life" },
                     new Brand { Name = "Keystone Light" },
                     new Brand { Name = "Natural Light" },
                     new Brand { Name = "Busch" },
                     new Brand { Name = "Icehouse" },
                     new Brand { Name = "Steel Reserve" },
                     new Brand { Name = "Kingfisher" },
                     new Brand { Name = "Bintang" },
                     new Brand { Name = "Tusker" },
                     new Brand { Name = "Castle Lager" },
                     new Brand { Name = "Windhoek" },
                     new Brand { Name = "Serengeti" },
                     new Brand { Name = "Club Beer" },
                     new Brand { Name = "Star Lager" },
                     new Brand { Name = "Primus" },
                     new Brand { Name = "Skopsko" },
                     new Brand { Name = "Efes Pilsen" },
                     new Brand { Name = "Zywiec" },
                     new Brand { Name = "Tatra" },
                     new Brand { Name = "Okocim" },
                     new Brand { Name = "Perła" },
                     new Brand { Name = "Browar Fortuna" },
                     new Brand { Name = "Browar Amber" },
                     new Brand { Name = "Browar Kormoran" },
                     new Brand { Name = "Browar Pinta" },
                     new Brand { Name = "Browar Artezan" },
                     new Brand { Name = "Browar Stu Mostów" },
                     new Brand { Name = "Browar Trzech Kumpli" },
                     new Brand { Name = "Browar Nepomucen" },
                     new Brand { Name = "Browar Brodacz" },
                     new Brand { Name = "Browar Raduga" },
                     new Brand { Name = "Browar Golem" },
                     new Brand { Name = "Browar Deer Bear" },
                     new Brand { Name = "Browar Solipiwko" },
                     new Brand { Name = "Browar Profesja" },
                     new Brand { Name = "Browar Widawa" },
                     new Brand { Name = "Browar Jan Olbracht" },
                     new Brand { Name = "Browar Zamkowy Cieszyn"},
                     new Brand { Name = "BrewDog" },
                     new Brand { Name = "Mikkeller" },
                     new Brand { Name = "To Øl" },
                     new Brand { Name = "Omnipollo" },
                     new Brand { Name = "Beavertown" },
                     new Brand { Name = "The Kernel" },
                     new Brand { Name = "Cloudwater" },
                     new Brand { Name = "Verdant Brewing" },
                     new Brand { Name = "Magic Rock" },
                     new Brand { Name = "Northern Monk" },
                     new Brand { Name = "Tiny Rebel" },
                     new Brand { Name = "Põhjala" },
                     new Brand { Name = "Lervig" },
                     new Brand { Name = "Nøgne Ø" },
                     new Brand { Name = "De Molen" },
                     new Brand { Name = "La Trappe" },
                     new Brand { Name = "Bosteels" },
                     new Brand { Name = "Dupont" },
                     new Brand { Name = "Cantillon" },
                     new Brand { Name = "3 Fonteinen" },
                     new Brand { Name = "Brasserie d’Achouffe" },
                     new Brand { Name = "Brasserie Dupont" },
                     new Brand { Name = "Brasserie de Rochefort" },
                     new Brand { Name = "Brasserie de la Senne" },
                     new Brand { Name = "Brasserie Fantôme" },
                     new Brand { Name = "Brasserie St. Bernardus" },
                     new Brand { Name = "Brasserie de Silly" },
                     new Brand { Name = "Brasserie Lefebvre" },
                     new Brand { Name = "Brasserie Caulier" },
                     new Brand { Name = "Brasserie Grain d’Orge" },
                     new Brand { Name = "Brasserie de Blaugies" },
                     new Brand { Name = "Brasserie de Bastogne" },
                     new Brand { Name = "Brasserie de la Lesse" },
                     new Brand { Name = "Brasserie de la Mule" },
                     new Brand { Name = "Brasserie de la Vallée du Giffre" },
                     new Brand { Name = "Brasserie du Mont Salève" },
                     new Brand { Name = "Brasserie du Pays Flamand" },
                     new Brand { Name = "Brasserie du Mont Blanc" },
                     new Brand { Name = "Brasserie du Bocq" },
                     new Brand { Name = "Brasserie de Bretagne" },
                     new Brand { Name = "Brasserie de la Loire" },
                     new Brand { Name = "Brasserie de la Pleine Lune" },
                     new Brand { Name = "Brasserie de la Rade" },
                     new Brand { Name = "Brasserie de la Seine" },
                     new Brand { Name = "Brasserie de la Vallée du Rhône" },
                     new Brand { Name = "Brasserie de la Vallée de Chevreuse" },
                     new Brand { Name = "Brasserie de la Vallée de l’Ouche" },
                     new Brand { Name = "Brasserie de la Vallée de Munster" },
                     new Brand { Name = "Brasserie de la Vallée de la Meuse" },
                     new Brand { Name = "Brasserie de la Vallée de la Semois" },
                     new Brand{ Name = "Brasserie de la Vallée de la Vesdre" }
                    );

                appDbContext.SaveChanges();
            }
        }
    }
}